/* automatically generated by rust-bindgen */

// #[link(name = "libeip1962cpp", kind = "static")]
extern "C" {
    pub fn run(
        i: *const ::std::os::raw::c_char,
        i_len: ::std::os::raw::c_int,
        o: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
